NumPy Arrays and Indexing

In [2]:
import numpy as np

1. Create a numpy array called ‘height in inches’ from a list 10 of numbers: [66, 68, 71, 64, 61, 74, 64, 65, 70, 71].

In [51]:
height_in_inches = np.array([66, 68,71, 64, 61, 74])
#print(height_in_inches)
height_in_inches
#height_in_inches.dtype

array([66, 68, 71, 64, 61, 74])

2. Create a new array called ‘height_in_feet’ and make its values equal to the values in the first array divided by 12.

In [59]:
height_in_feet = np.array([66, 68,71, 64, 61, 74])
#print(height_in_feet)
#height_in_feet
#height_in_feet.dtype
print(height_in_feet/12)
#print(a)

[5.5        5.66666667 5.91666667 5.33333333 5.08333333 6.16666667]


3. Create a 5x5 array of zeros. 

In [38]:
a = np.zeros((5,5), dtype = int)
print(a.dtype)
print(a)

int64
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


4. Create an array of random floating point numbers between 0 and 100.

In [65]:
#rfloat = np.random.uniform(0,101,100)
#print(rfloat)
#rfloat.dtype
rfloat = (np.random.random(5)) * 100
print(rfloat)
rfloat.dtype

[36.66062141 79.63053769 54.36360431 31.3409902  81.68841865]


dtype('float64')

5. Create an array of numbers from 0 to 75 in increments of 5.

In [66]:
a = np.arange(0,76,5)
print(a.dtype)
#print(a)
a

int64


array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75])